theme: jekyll-theme-leap-day
title: ZeroZipp
description: Our github page
downloads:
  apk: false
  zip: true
  apk_url: null
  zip_url: https://github.com/ZeroZipp/Bypackt/releases/latest/download/1.12.2-Bypackt.zip
links:
  home: /
  mods: /mods
  bypackt: /bypackt
